flowchart TD
    A[Main Menu] -->|Choose an action| B{Actions}
    B -->|Checkin Habit streak| C[set_milestone_for_habit]
    B -->|Create Habit| D[Add Habit]
    B -->|Read Items| E[print_habits_as_list]
    B -->|Complete Habit| F[complete_habit]
    B -->|Create Predefined Habit| G[predefined_habit]
    B -->|Habit Statistics| H[view_statistics]
    B -->|Exit| I[Exit Application]

    C --> J[Check Habit ID]
    J -->|Valid ID| K[Mark Habit as Complete]
    J -->|Invalid ID| L[Error Message]

    D --> M[Ask for Name]
    D --> N[Ask for Periodicity]
    D --> O[Ask for Target Duration]
    D --> P[Compute Target Date]
    D --> Q[add_habit]

    F --> R[List All Habits]
    R --> S[Ask for Habit ID]
    S -->|Valid ID| T[Mark Habit Complete]
    S -->|Invalid ID| U[Error Message]

    G --> V[Choose Predefined Habit]
    G --> W[Choose Periodicity]
    G --> X[Ask for Target Duration]
    G --> Y[Compute Target Date]
    G --> Z[add_habit]

    H --> AA[Choose Statistics Option]
    AA -->|Get Longest Streak| AB[Analyze Habits]
    AB --> AC[Display Longest Streak]
    AC --> AD[Display Daily Habits]
    AC --> AE[Display Weekly Habits]

    click C href "javascript:alert('Navigate to set_milestone_for_habit');"
    click D href "javascript:alert('Navigate to add_habit');"
    click E href "javascript:alert('Navigate to print_habits_as_list');"
    click F href "javascript:alert('Navigate to complete_habit');"
    click G href "javascript:alert('Navigate to predefined_habit');"
    click H href "javascript:alert('Navigate to view_statistics');"

%% Individual node styling. Try the visual editor toolbar for easier styling!
%%    style E color:#FFFFFF, fill:#AA00FF, stroke:#AA00FF
    style D color:#FFFFFF, stroke:#00C853, fill:#00C853
    style E color:#FFFFFF, stroke:#00C853, fill:#00C853
    style C color:#FFFFFF, stroke:#00C853, fill:#00C853
    style H color:#FFFFFF, stroke:#00C853, fill:#00C853
    style G color:#FFFFFF, stroke:#00C853, fill:#00C853
    style F color:#FFFFFF, stroke:#00C853, fill:#00C853
    style A color:#FFFFFF, stroke:#2962FF, fill:#2962FF
    style I color:#FFFFFF, stroke:#00C853, fill:#00C853
